catalyst/moodle-local_smartmedia

- classes/output/renderer.php
- classes/output/report_table.php
- report.php
Fix an issue where file download was not displaying for report if a region has not been selected.
> Issue#36: Overview report - File download not displaying

- classes/output/report_summary.php
- tests/report_summary_test.php
> Issue#49: fix report summary total error

- classes/ffprobe.php
- tests/ffprobe_test.php
- tests/fixtures/ffprobe_test_fixture.php
Patch includes test coverage and fixture
> metadata extraction now handles case where ffprobe only returns partial data from file

- classes/conversion.php
- lib.php
- tests/conversion_test.php
as well as initial checks to make sure the smartmedia file correctly matches the source file
> add pluginfile for serving of smartmedia assets

- classes/conversion.php
- lib.php
- tests/conversion_test.php
- tests/fixtures/conversion_test_fixture.php
rewrites playlist URLs to allow delivery from Moodle
> Issue#96 playlist urls

- classes/task/extract_metadata.php
- tests/extract_metadata_test.php
> update metadata extraction to ignore already converted files

- classes/conversion.php
- tests/conversion_test.php
> add method and test for will convert

- classes/utility.php
- lib.php
- tests/utility_test.php
> add method to filter pluginfile arguments

- classes/conversion.php
- classes/task/report_process.php
- version.php
> Issue 143: Add a missing file check before conversion

- tests/conversion_test.php
> Issue #149: Backwards compatability for PHPUnit 6

- db/upgrade.php
- version.php
> Issue #147: Updated upgrade script with new table information

- classes/conversion.php
Partially addressed #145 . Allows conversion task to avoid missing files
> Issue 148: Skip missing files from creating conversion

- classes/task/report_process.php
> Issue #154: Fix Scheduled task when no files have been converted

- classes/aws_elastic_transcoder.php
> Issue #158: Added caching to preset information

- classes/ffprobe.php
> Issue #166: Updated ffprobe to use local temp file instead of shared temp

- classes/aws_api.php
- classes/aws_s3.php
- classes/provision.php
- classes/queue_process.php
- tests/aws_api_test.php
- version.php
> Issue #163: Fixed more proxy points

- classes/task/extract_metadata.php
> Issue #170: Changed query to work backwards from latest file

- classes/task/extract_metadata.php
> Issue #181: Updated chunk size of extract size to 20 files

- classes/task/extract_metadata.php
- db/install.xml
- db/upgrade.php
- version.php
> Added table for recording metadata failures

- classes/conversion.php
- classes/task/report_process.php
https://tracker.moodle.org/browse/MDL-71198
> Partially reverted the file lookback commit, see MDL-71198

- cli/provision.php
> Add identifier flag to provision script

- db/upgrade.php
- version.php
> Add missing foreign key for 'contenthash' upgrades

- classes/conversion.php
- classes/ffprobe.php
- classes/output/renderer.php
- classes/output/report_summary.php
- classes/output/report_table.php
- classes/pricing/aws_base_product.php
- classes/pricing/aws_ets_product.php
- classes/pricing/aws_rekog_product.php
- classes/pricing/aws_transcribe_product.php
- classes/pricing_calculator.php
- classes/privacy/provider.php
- classes/task/extract_metadata.php
- classes/task/process_conversions.php
- classes/task/report_process.php
- classes/utility.php
- db/upgrade.php
- db/upgradelib.php
- lib.php
- tests/aws_ets_product_test.php
- tests/extract_metadata_test.php
- tests/ffprobe_test.php
- tests/location_transcode_pricing_test.php
- tests/pricing_calculator_test.php
- tests/report_process_test.php
- tests/utility_test.php
> [#212] Fix Unexpected Moodle Internal errors/warnings in CI

- db/install.xml
- db/upgrade.php
- tests/location_transcode_pricing_test.php
- tests/pricing_calculator_test.php
- tests/smartmedia_testcase.php
- version.php
Normally taking 90ms to complete, drops down to 3ms
> perf(db): add index to improve query times
